spring:
  datasource:
    url: jdbc:mysql://localhost:3306/phone_db
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: true

telegram:
  bot:
    username: "@OldPhoneBot"
    token: "8163853097:AAGpjtmupYG4rjeCNcV5xq5z4e2ltTCBKeU"

admin:
  password: "Java2023"