spring:
  datasource:
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}

  jpa:
    hibernate:
      ddl-auto: update # 데이터베이스 스키마를 유지하려면 'update'로 설정하세요.
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: true

telegram:
  bot:
    username: "@OldPhoneBot"
    token: "${TELEGRAM_BOT_TOKEN}"

admin:
  password: "${ADMIN_PASSWORD}"

cloudinary:
  cloud_name: "${CLOUDINARY_CLOUD_NAME}"
  api_key: "${CLOUDINARY_API_KEY}"
  api_secret: "${CLOUDINARY_API_SECRET}"

